# Base image
FROM ubuntu:22.04

# Install required packages
RUN apt-get update && apt-get install -y \
    gcc g++ openjdk-17-jdk && \
    apt-get clean

# Set working directory inside container
WORKDIR /app

# By default container runs bash
CMD ["bash"]
