import React from 'react';

interface LearnMorePanelProps {
    isOpen: boolean;
    onClose: () => void;
    title: string;
    content: string;
    loading: boolean;
}

const LearnMorePanel: React.FC<LearnMorePanelProps> = ({ isOpen, onClose, title, content, loading }) => {
    return (
        <div
            className={`fixed inset-0 z-50 overflow-hidden ${isOpen ? 'pointer-events-auto' : 'pointer-events-none'}`}
            aria-labelledby="slide-over-title"
            role="dialog"
            aria-modal="true"
        >
            <div className={`absolute inset-0 bg-gray-500 bg-opacity-75 transition-opacity duration-300 ease-in-out ${isOpen ? 'opacity-100' : 'opacity-0'}`} onClick={onClose}></div>

            <div className={`fixed inset-y-0 right-0 max-w-xl w-full flex transform transition-transform duration-300 ease-in-out ${isOpen ? 'translate-x-0' : 'translate-x-full'}`}>
                <div className="relative w-full bg-white shadow-2xl flex flex-col h-full">
                    {/* Header */}
                    <div className="px-6 py-4 bg-blue-600 text-white flex items-center justify-between shadow-md">
                        <h2 className="text-lg font-bold" id="slide-over-title">AI Explanation</h2>
                        <button onClick={onClose} className="text-blue-100 hover:text-white focus:outline-none">
                            <span className="sr-only">Close panel</span>
                            <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                            </svg>
                        </button>
                    </div>

                    {/* Content */}
                    <div className="relative flex-1 px-6 py-6 overflow-y-auto">
                        <h3 className="text-xl font-bold text-gray-900 mb-4">{title}</h3>

                        {loading ? (
                            <div className="space-y-4 animate-pulse">
                                <div className="h-4 bg-gray-200 rounded w-3/4"></div>
                                <div className="h-4 bg-gray-200 rounded w-full"></div>
                                <div className="h-4 bg-gray-200 rounded w-5/6"></div>
                                <div className="h-32 bg-gray-100 rounded w-full mt-6"></div>
                            </div>
                        ) : (
                            <div className="prose prose-blue max-w-none text-gray-700 space-y-4 whitespace-pre-line">
                                {content ? content : "No explanation available."}
                            </div>
                        )}
                    </div>

                    {/* Footer */}
                    <div className="border-t border-gray-200 px-6 py-4 bg-gray-50">
                        <p className="text-xs text-center text-gray-500">
                            Generated by AI. Content may vary.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default LearnMorePanel;
